import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const BRAND_URL = 'https://brand.mines.edu/';

export function writeBrandNotes(outDir: string): void {
  const lines: string[] = [
    '# Brand compliance notes',
    '',
    `All decisions on this site are keyed against the official Mines brand guide at ${BRAND_URL}. This document lists every color, font, spacing, and logo choice used in the handoff bundle so that Mines Communications and Marketing can audit compliance at a glance before Divi deployment.`,
    '',
    '## Colors',
    '',
    `Per ${BRAND_URL} the Mines palette uses a core blue, a secondary deep blue, a supporting light blue, a warm red accent, and a neutral gray family. Values below are the HEX specifications used across the site.`,
    '',
    '| Name | HEX | Use on site | Source |',
    '|------|-----|-------------|--------|',
    `| Mines Blue | \`#21314D\` | Primary brand color: header background, H1 and H2 text on light surfaces, primary button fill | ${BRAND_URL} |`,
    `| Deep Blue | \`#263F6A\` | Hover state on primary buttons, dense data panels | ${BRAND_URL} |`,
    `| Light Blue | \`#92A2BD\` | Secondary accents, muted rules, chart series | ${BRAND_URL} |`,
    `| Pale Blue | \`#CED5DD\` | Tint backgrounds for stat strips and quote blocks | ${BRAND_URL} |`,
    `| Mines Red | \`#D2492A\` | Sparingly for link hover, urgent callouts, and the "apply / contact" CTA accent. Never as body text color | ${BRAND_URL} |`,
    `| Gray | \`#B2B4B3\` | Body text on dark surfaces, secondary icons | ${BRAND_URL} |`,
    `| Silver | \`#8B8D8E\` | Captions, form helper text, footnotes | ${BRAND_URL} |`,
    '',
    '### Color usage rules',
    '',
    `- Mines Blue \`#21314D\` is the dominant brand color. It sets the navigation bar, footer, and H1 / H2 on white backgrounds.`,
    `- Mines Red \`#D2492A\` is an accent only. Never use for body text. Never for the nav. Contact and apply CTAs may use it.`,
    `- Pale Blue \`#CED5DD\` is the preferred tint background for stat strips on white pages, preserving the required 4.5:1 contrast with Mines Blue text.`,
    `- Neutrals (Gray, Silver) are reserved for secondary text and non-critical UI chrome.`,
    '',
    '## Typography',
    '',
    `The Mines brand guide at ${BRAND_URL} specifies Open Sans as the primary web typeface. The site loads Open Sans from Google Fonts with the weights required for the brand hierarchy.`,
    '',
    '| Weight | Use | Example |',
    '|--------|-----|---------|',
    '| 400 (Regular) | Body copy, descriptive paragraphs | Paragraph text at 16-18 px |',
    '| 500 (Medium) | Inline emphasis, form labels, button labels | Nav items, CTA button text |',
    '| 600 (Semibold) | H3, H4 subheadings | Section subheads, card titles |',
    '| 700 (Bold) | H1, H2 on hero and section headers | Page titles, primary section headings |',
    '',
    '### Typography rules',
    '',
    `- Page source: \`https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap\`.`,
    `- Title case is reserved for page titles and proper nouns.`,
    `- Sentence case is standard for section headings and body copy.`,
    `- No em-dashes. Replace with commas, colons, or restructured sentences.`,
    `- No emojis.`,
    `- American English spelling.`,
    '',
    '## Spacing',
    '',
    `The site uses an 8-pixel base spacing scale which aligns with the Mines brand guide at ${BRAND_URL}. Tailwind v4 utilities used in build map to this scale cleanly.`,
    '',
    '| Token | Pixels | Use |',
    '|-------|--------|-----|',
    '| `xs` | 8 px | Icon-to-text gap, tight inline spacing |',
    '| `sm` | 16 px | List item spacing, compact card internal padding |',
    '| `md` | 24 px | Default paragraph gap, card internal padding |',
    '| `lg` | 48 px | Major section padding (top and bottom) |',
    '| `xl` | 96 px | Hero block vertical padding on desktop |',
    '',
    '### Spacing rules',
    '',
    '- Container max width: 1200 px (per Mines web system).',
    '- Section vertical rhythm: 96 px desktop, 64 px tablet, 48 px mobile.',
    '- Card internal padding: 24 px on all sides.',
    '- Grid gutter: 24 px.',
    '',
    '## Logo',
    '',
    `Official logo assets must come from ${BRAND_URL}. The site uses the wordmark "Colorado School of Mines" and the "Mines Automotive Engineering Program" sub-brand lockup.`,
    '',
    '### Logo rules',
    '',
    '- Never re-color the primary Mines logo outside of approved brand colors.',
    '- Clear space around the logo is at minimum the height of the letter M.',
    '- Minimum logo height is 32 px on web, 0.5 in in print.',
    '- The primary header uses the horizontal Mines Automotive sub-brand lockup on a Mines Blue background.',
    '- Footer uses the Mines wordmark in white on Mines Blue.',
    '- Do not place the logo on photographic backgrounds without a solid color plate behind it.',
    '',
    '## Accessibility gates',
    '',
    '- WCAG 2.1 AA compliance is a release gate (per project CLAUDE.md).',
    '- All brand color pairings used on the site have been selected to meet or exceed 4.5:1 contrast for body text and 3:1 for large text.',
    '- Mines Red on white passes for large text only. Never use on body copy.',
    '- Light Blue on white does not pass body text contrast. Never use for readable type; decorative only.',
    '',
    `## Reference`,
    '',
    `- Mines brand guide (authoritative): ${BRAND_URL}`,
    `- Project hard rules: see repo \`CLAUDE.md\`.`,
    ''
  ];

  writeFileSync(join(outDir, 'brand-compliance-notes.md'), lines.join('\n'));
}
